name: miniaudio_ffi
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  ffi: ^2.1.0
  # path: ^1.8.0

dev_dependencies:
  ffigen: ^9.0.1
  lints: ^2.0.0
  test: ^1.21.0


ffigen:
  output: 'lib/src/miniaudio_bindings.dart'
  headers:
    entry-points:
      - 'src/miniaudio.h'
    include-directives:
      - '**miniaudio.h'
  name: 'MiniAudioBindings'
  preamble: '// ignore_for_file: camel_case_types, non_constant_identifier_names, constant_identifier_names, unused_field'
  unions:
    dependency-only: opaque
  functions:
    symbol-address:
      include:
        - '.*'
  comments:
    style: any
    length: full
  description: 'FFI bindings to miniaudio library'